name: RunsafeBank
main: no.runsafe.runsafebank.Plugin
version: 1.0.@BUILD@
authors: []
depend: []
description:
commands:
  viewbank:
    description: Opens a players bank
  clearbank:
    description: Deletes a players bank
